apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs 
spec:
  storageClassName: etcd-backup
  capacity:
    storage: 2Gi
  volumeMode: Filesystem  
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /mnt/etcd-backup
    server: 192.168.1.4 
  persistentVolumeReclaimPolicy: Delete
