apiVersion: v1
kind: PersistentVolumeClaim
namespace: etcd-backup
metadata:
  name: pvc-nfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: pv-nfs
  storageClassName: etcd-backup
